[package]
name = "jakelogemann"
description = "my (personal) crate!"
version = "0.0.1"
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
